name: PR Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  up-to-date:
    name: Check Branch is Up-to-date
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if branch is up-to-date
        run: |
          git fetch origin ${{ github.base_ref }}
          BEHIND=$(git rev-list --count HEAD..origin/${{ github.base_ref }})
          if [ "$BEHIND" -gt 0 ]; then
            echo "::warning::Branch is $BEHIND commit(s) behind ${{ github.base_ref }}. Consider rebasing."
          else
            echo "Branch is up-to-date with ${{ github.base_ref }}"
          fi

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          allow-prereleases: true

      - name: Install UV
        uses: astral-sh/setup-uv@v4

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  django-checks:
    name: Django Health Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          allow-prereleases: true

      - name: Install UV
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync

      - name: Run Django system checks
        run: uv run python config/manage.py check

      - name: Check for missing migrations
        run: uv run python config/manage.py makemigrations --check --dry-run
